// modules/accessibility/criteria.js — WCAG 2.2 Level A + AA success-criteria
// database (pure data, no DOM). Adapted verbatim in spirit from the AccessCheck
// source tool (accesscheck/src/criteria.js): the same criterion rows, component
// tags, site-type scoping, and automation metadata, trimmed to the fields the
// VibeCheck readiness scorer needs.
//
// Each row:
//   id         official SC number (e.g. "1.1.1"); reinforcement rows carry a
//              "-suffix" (e.g. "1.1.1-pdf") but share the base SC.
//   name       official short name
//   level      "A" | "AA"
//   principle  "perceivable" | "operable" | "understandable" | "robust"
//   plain      plain-English one-liner
//   failure    a common real-world failure example
//   components which component types this applies to (see COMPONENTS)
//   siteTypes  site types where relevant, or "all"
//   auto       "auto" | "partial" | "manual" — how much a tool can catch

/** Component types a project can declare it contains. */
export const COMPONENTS = [
  { id: 'text', label: 'Text content', always: true },
  { id: 'images', label: 'Images & icons' },
  { id: 'forms', label: 'Forms & inputs' },
  { id: 'navigation', label: 'Navigation & menus' },
  { id: 'links', label: 'Links & buttons' },
  { id: 'video', label: 'Video' },
  { id: 'audio', label: 'Audio' },
  { id: 'modals', label: 'Modals & dialogs' },
  { id: 'tables', label: 'Data tables' },
  { id: 'carousels', label: 'Carousels & auto-updating content' },
  { id: 'custom', label: 'Custom widgets (ARIA)' },
  { id: 'pdf', label: 'PDFs & documents' },
  { id: 'keyboard', label: 'Keyboard interaction', always: true },
  { id: 'color', label: 'Color & contrast', always: true },
];

/** Site types the checklist can be scoped to. */
export const SITE_TYPES = [
  { id: 'ecommerce', label: 'E-commerce / checkout' },
  { id: 'saas', label: 'SaaS / web app' },
  { id: 'blog', label: 'Blog / content site' },
  { id: 'government', label: 'Government / public sector' },
  { id: 'marketing', label: 'Marketing / brochure site' },
];

/** Compliance levels, in inclusive order. */
export const LEVELS = ['A', 'AA'];

const P = 'perceivable';
const O = 'operable';
const U = 'understandable';
const R = 'robust';

/** WCAG 2.2 Level A + AA success criteria (4.1.1 Parsing intentionally absent). */
export const CRITERIA = [
  // ─────────────────── 1 Perceivable ───────────────────
  { id: '1.1.1', name: 'Non-text Content', level: 'A', principle: P,
    plain: 'All images, icons, and non-text content have text alternatives.',
    failure: 'A product photo with no alt text; an icon-only "delete" button announced as just "button".',
    components: ['images'], siteTypes: 'all', auto: 'partial' },
  { id: '1.2.1', name: 'Audio-only and Video-only (Prerecorded)', level: 'A', principle: P,
    plain: 'Prerecorded audio-only has a transcript; video-only has a transcript or audio description.',
    failure: 'A podcast episode published with no transcript.',
    components: ['audio', 'video'], siteTypes: 'all', auto: 'manual' },
  { id: '1.2.2', name: 'Captions (Prerecorded)', level: 'A', principle: P,
    plain: 'Prerecorded video with audio has synchronized captions.',
    failure: 'A promo video with no captions.',
    components: ['video'], siteTypes: 'all', auto: 'manual' },
  { id: '1.2.3', name: 'Audio Description or Media Alternative (Prerecorded)', level: 'A', principle: P,
    plain: 'Prerecorded video provides audio description or a full text alternative.',
    failure: 'A tutorial that shows steps on screen with no narration and no transcript.',
    components: ['video'], siteTypes: 'all', auto: 'manual' },
  { id: '1.2.4', name: 'Captions (Live)', level: 'AA', principle: P,
    plain: 'Live audio in synchronized media has real-time captions.',
    failure: 'A live product launch stream with no live captioning.',
    components: ['video', 'audio'], siteTypes: 'all', auto: 'manual' },
  { id: '1.2.5', name: 'Audio Description (Prerecorded)', level: 'AA', principle: P,
    plain: 'Prerecorded video provides audio description of visual detail.',
    failure: 'A recorded demo where the presenter says "click here" with no described target.',
    components: ['video'], siteTypes: 'all', auto: 'manual' },
  { id: '1.3.1', name: 'Info and Relationships', level: 'A', principle: P,
    plain: 'Structure conveyed visually is also available in the code (headings, lists, labels, table headers).',
    failure: 'Bold blue text used to look like a heading but marked up as a plain div.',
    components: ['text'], siteTypes: 'all', auto: 'partial' },
  { id: '1.3.2', name: 'Meaningful Sequence', level: 'A', principle: P,
    plain: 'The reading and navigation order in the code makes sense.',
    failure: 'A two-column layout whose code order interleaves columns nonsensically.',
    components: ['text'], siteTypes: 'all', auto: 'manual' },
  { id: '1.3.3', name: 'Sensory Characteristics', level: 'A', principle: P,
    plain: 'Instructions do not rely on shape, size, position, or sound alone.',
    failure: '"Press the green button to continue" with no other label distinguishing it.',
    components: ['text'], siteTypes: 'all', auto: 'manual' },
  { id: '1.3.4', name: 'Orientation', level: 'AA', principle: P,
    plain: 'Content is not locked to a single display orientation (portrait or landscape).',
    failure: 'A checkout that only renders in portrait and shows "please rotate" in landscape.',
    components: ['text'], siteTypes: 'all', auto: 'partial' },
  { id: '1.3.5', name: 'Identify Input Purpose', level: 'AA', principle: P,
    plain: 'Common input fields declare their purpose via autocomplete attributes.',
    failure: 'A shipping-address form with no autocomplete attributes, so browsers cannot autofill.',
    components: ['forms'], siteTypes: ['ecommerce', 'saas', 'government'], auto: 'partial' },
  { id: '1.4.1', name: 'Use of Color', level: 'A', principle: P,
    plain: 'Color is not the only way information is conveyed.',
    failure: 'A form error shown only by turning a field red.',
    components: ['color'], siteTypes: 'all', auto: 'manual' },
  { id: '1.4.2', name: 'Audio Control', level: 'A', principle: P,
    plain: 'Audio that plays automatically for 3+ seconds can be paused or stopped.',
    failure: 'A background video with sound that auto-plays with no mute button.',
    components: ['audio', 'video'], siteTypes: 'all', auto: 'manual' },
  { id: '1.4.3', name: 'Contrast (Minimum)', level: 'AA', principle: P,
    plain: 'Text has a contrast ratio of at least 4.5:1 (3:1 for large text).',
    failure: 'Light-grey placeholder text on a white input at 2.5:1.',
    components: ['color'], siteTypes: 'all', auto: 'auto' },
  { id: '1.4.4', name: 'Resize Text', level: 'AA', principle: P,
    plain: 'Text can be resized up to 200% without loss of content or function.',
    failure: 'A fixed-height header that hides its nav links when text is enlarged.',
    components: ['text'], siteTypes: 'all', auto: 'manual' },
  { id: '1.4.5', name: 'Images of Text', level: 'AA', principle: P,
    plain: 'Real text is used instead of images of text (except logos).',
    failure: 'A "Sale 50% off" hero rendered as a flat image, unreadable and blurry when zoomed.',
    components: ['images'], siteTypes: ['ecommerce', 'marketing'], auto: 'manual' },
  { id: '1.4.10', name: 'Reflow', level: 'AA', principle: P,
    plain: 'Content reflows to a single column at 320px wide with no horizontal scrolling.',
    failure: 'A data-heavy dashboard that forces horizontal scroll on mobile.',
    components: ['text'], siteTypes: 'all', auto: 'manual' },
  { id: '1.4.11', name: 'Non-text Contrast', level: 'AA', principle: P,
    plain: 'UI components and meaningful graphics have at least 3:1 contrast against adjacent colors.',
    failure: 'A light-grey input border on white at 1.4:1 — invisible to low-vision users.',
    components: ['color'], siteTypes: 'all', auto: 'manual' },
  { id: '1.4.12', name: 'Text Spacing', level: 'AA', principle: P,
    plain: 'No loss of content when users override line height and letter/word spacing.',
    failure: 'Text in fixed-height buttons gets cut off when line-height is increased.',
    components: ['text'], siteTypes: 'all', auto: 'manual' },
  { id: '1.4.13', name: 'Content on Hover or Focus', level: 'AA', principle: P,
    plain: 'Tooltips/popovers shown on hover or focus are dismissable, hoverable, and persistent.',
    failure: 'A tooltip that vanishes the moment you move the mouse toward it.',
    components: ['custom'], siteTypes: 'all', auto: 'manual' },

  // ─────────────────── 2 Operable ───────────────────
  { id: '2.1.1', name: 'Keyboard', level: 'A', principle: O,
    plain: 'All functionality is available from a keyboard.',
    failure: 'A custom dropdown that only opens on mouse click and cannot be reached by Tab.',
    components: ['keyboard'], siteTypes: 'all', auto: 'manual' },
  { id: '2.1.2', name: 'No Keyboard Trap', level: 'A', principle: O,
    plain: 'Keyboard focus can always move away from any component.',
    failure: 'A modal that traps Tab focus with no way to close it via keyboard.',
    components: ['keyboard'], siteTypes: 'all', auto: 'manual' },
  { id: '2.1.4', name: 'Character Key Shortcuts', level: 'A', principle: O,
    plain: 'Single-character keyboard shortcuts can be turned off, remapped, or are focus-scoped.',
    failure: 'Pressing "j"/"k" navigates a feed even while typing in a comment box.',
    components: ['custom'], siteTypes: ['saas'], auto: 'manual' },
  { id: '2.2.1', name: 'Timing Adjustable', level: 'A', principle: O,
    plain: 'Time limits can be turned off, adjusted, or extended.',
    failure: 'A checkout that silently expires the cart after 10 minutes with no warning.',
    components: ['forms'], siteTypes: ['ecommerce', 'saas', 'government'], auto: 'manual' },
  { id: '2.2.2', name: 'Pause, Stop, Hide', level: 'A', principle: O,
    plain: 'Moving, blinking, or auto-updating content can be paused, stopped, or hidden.',
    failure: 'A hero carousel that auto-advances every 3s with no pause button.',
    components: ['carousels'], siteTypes: 'all', auto: 'partial' },
  { id: '2.3.1', name: 'Three Flashes or Below Threshold', level: 'A', principle: O,
    plain: 'Nothing flashes more than three times per second.',
    failure: 'A promotional GIF that strobes red/white several times a second.',
    components: ['video', 'carousels'], siteTypes: 'all', auto: 'manual' },
  { id: '2.4.1', name: 'Bypass Blocks', level: 'A', principle: O,
    plain: 'A mechanism (e.g. skip link) bypasses repeated blocks of content.',
    failure: 'No skip link, so keyboard users tab through 30 nav items on every page.',
    components: ['navigation'], siteTypes: 'all', auto: 'partial' },
  { id: '2.4.2', name: 'Page Titled', level: 'A', principle: O,
    plain: 'Each page has a descriptive, unique title.',
    failure: 'Every page titled "Home" or "Untitled".',
    components: ['text'], siteTypes: 'all', auto: 'partial' },
  { id: '2.4.3', name: 'Focus Order', level: 'A', principle: O,
    plain: 'Focus moves in an order that preserves meaning and operability.',
    failure: 'Tab jumps from the header straight to the footer, then back to the form.',
    components: ['keyboard'], siteTypes: 'all', auto: 'manual' },
  { id: '2.4.4', name: 'Link Purpose (In Context)', level: 'A', principle: O,
    plain: 'The purpose of each link is clear from its text or context.',
    failure: 'A page of "Read more" links with no distinguishing context.',
    components: ['links'], siteTypes: 'all', auto: 'partial' },
  { id: '2.4.5', name: 'Multiple Ways', level: 'AA', principle: O,
    plain: 'More than one way exists to find a page (nav, search, sitemap).',
    failure: 'A store with hundreds of products reachable only by clicking through categories, no search.',
    components: ['navigation'], siteTypes: ['ecommerce', 'blog', 'government', 'marketing'], auto: 'manual' },
  { id: '2.4.6', name: 'Headings and Labels', level: 'AA', principle: O,
    plain: 'Headings and form labels describe their topic or purpose.',
    failure: 'A form field labeled just "Input" or a section headed "Section 2".',
    components: ['text'], siteTypes: 'all', auto: 'manual' },
  { id: '2.4.7', name: 'Focus Visible', level: 'AA', principle: O,
    plain: 'Keyboard focus is always visibly indicated.',
    failure: 'A CSS reset that sets outline:none globally, hiding all focus.',
    components: ['keyboard'], siteTypes: 'all', auto: 'manual' },
  { id: '2.4.11', name: 'Focus Not Obscured (Minimum)', level: 'AA', principle: O,
    plain: 'A focused element is not entirely hidden by sticky headers, footers, or other content.',
    failure: 'A sticky cookie banner that covers the input you just tabbed to.',
    components: ['keyboard'], siteTypes: 'all', auto: 'manual' },
  { id: '2.5.1', name: 'Pointer Gestures', level: 'A', principle: O,
    plain: 'Multipoint or path-based gestures have a single-pointer alternative.',
    failure: 'A carousel advanced only by a two-finger swipe.',
    components: ['carousels', 'custom'], siteTypes: 'all', auto: 'manual' },
  { id: '2.5.2', name: 'Pointer Cancellation', level: 'A', principle: O,
    plain: 'Actions triggered by a single pointer can be aborted or undone (fire on up-event).',
    failure: 'A "Delete" that fires on mouse-down, so an accidental press cannot be aborted.',
    components: ['links', 'custom'], siteTypes: 'all', auto: 'manual' },
  { id: '2.5.3', name: 'Label in Name', level: 'A', principle: O,
    plain: 'A control’s accessible name contains its visible label text.',
    failure: 'A button reading "Search" with aria-label="Find products" — voice control "click Search" fails.',
    components: ['forms', 'links', 'custom'], siteTypes: 'all', auto: 'partial' },
  { id: '2.5.4', name: 'Motion Actuation', level: 'A', principle: O,
    plain: 'Functions triggered by device motion have a UI alternative and can be disabled.',
    failure: '"Shake to undo" with no visible undo button.',
    components: ['custom'], siteTypes: ['saas'], auto: 'manual' },
  { id: '2.5.7', name: 'Dragging Movements', level: 'AA', principle: O,
    plain: 'Anything done by dragging has a single-tap/click alternative.',
    failure: 'A kanban board where cards can only be moved by dragging.',
    components: ['custom'], siteTypes: ['saas'], auto: 'manual' },
  { id: '2.5.8', name: 'Target Size (Minimum)', level: 'AA', principle: O,
    plain: 'Interactive targets are at least 24×24 CSS px (or have adequate spacing).',
    failure: 'A 12px close "×" on a modal, hard to tap on mobile.',
    components: ['links', 'forms', 'custom'], siteTypes: 'all', auto: 'partial' },

  // ─────────────────── 3 Understandable ───────────────────
  { id: '3.1.1', name: 'Language of Page', level: 'A', principle: U,
    plain: 'The page’s primary language is set in the code.',
    failure: 'Missing lang attribute, so screen readers pick the wrong voice/pronunciation.',
    components: ['text'], siteTypes: 'all', auto: 'auto' },
  { id: '3.1.2', name: 'Language of Parts', level: 'AA', principle: U,
    plain: 'Passages in a different language are marked with a lang attribute.',
    failure: 'A French quotation in an English page with no lang marking, read in an English voice.',
    components: ['text'], siteTypes: 'all', auto: 'partial' },
  { id: '3.2.1', name: 'On Focus', level: 'A', principle: U,
    plain: 'Moving focus to a component does not trigger an unexpected context change.',
    failure: 'Focusing a select auto-navigates to a new page.',
    components: ['forms'], siteTypes: 'all', auto: 'manual' },
  { id: '3.2.2', name: 'On Input', level: 'A', principle: U,
    plain: 'Changing a setting does not automatically cause an unexpected context change.',
    failure: 'Selecting a country from a dropdown immediately reloads the whole page.',
    components: ['forms'], siteTypes: 'all', auto: 'manual' },
  { id: '3.2.3', name: 'Consistent Navigation', level: 'AA', principle: U,
    plain: 'Navigation appears in the same relative order across pages.',
    failure: 'The nav menu reorders its links on different pages.',
    components: ['navigation'], siteTypes: 'all', auto: 'manual' },
  { id: '3.2.4', name: 'Consistent Identification', level: 'AA', principle: U,
    plain: 'Components with the same function are labeled consistently.',
    failure: 'Search is a magnifying glass on one page and the word "Find" on another.',
    components: ['navigation', 'custom'], siteTypes: 'all', auto: 'manual' },
  { id: '3.2.6', name: 'Consistent Help', level: 'A', principle: U,
    plain: 'Help mechanisms (contact, chat, FAQ) appear in a consistent location across pages.',
    failure: 'The support chat is bottom-right on one page and hidden in the footer on another.',
    components: ['navigation'], siteTypes: ['ecommerce', 'saas', 'government'], auto: 'manual' },
  { id: '3.3.1', name: 'Error Identification', level: 'A', principle: U,
    plain: 'Input errors are identified and described in text.',
    failure: 'A form that just highlights fields red with no text explanation.',
    components: ['forms'], siteTypes: 'all', auto: 'manual' },
  { id: '3.3.2', name: 'Labels or Instructions', level: 'A', principle: U,
    plain: 'Inputs have labels or instructions when needed.',
    failure: 'A date field labeled only by placeholder text that disappears on typing.',
    components: ['forms'], siteTypes: 'all', auto: 'partial' },
  { id: '3.3.3', name: 'Error Suggestion', level: 'AA', principle: U,
    plain: 'When an input error is detected, a correction suggestion is offered if known.',
    failure: '"Invalid input" with no hint about what was wrong.',
    components: ['forms'], siteTypes: 'all', auto: 'manual' },
  { id: '3.3.4', name: 'Error Prevention (Legal, Financial, Data)', level: 'AA', principle: U,
    plain: 'Submissions with legal/financial/data consequences are reversible, checked, or confirmed.',
    failure: 'An order placed instantly on button click with no confirmation screen.',
    components: ['forms'], siteTypes: ['ecommerce', 'saas', 'government'], auto: 'manual' },
  { id: '3.3.7', name: 'Redundant Entry', level: 'A', principle: U,
    plain: 'Information already entered is auto-populated or selectable, not re-typed.',
    failure: 'A checkout forcing the user to retype their address for billing.',
    components: ['forms'], siteTypes: ['ecommerce', 'saas', 'government'], auto: 'manual' },
  { id: '3.3.8', name: 'Accessible Authentication (Minimum)', level: 'AA', principle: U,
    plain: 'Login does not require a cognitive test (a puzzle or remembered code) with no alternative.',
    failure: 'A login that blocks paste and requires solving a distorted-text CAPTCHA with no alternative.',
    components: ['forms'], siteTypes: ['ecommerce', 'saas', 'government'], auto: 'manual' },

  // ─────────────────── 4 Robust ───────────────────
  { id: '4.1.2', name: 'Name, Role, Value', level: 'A', principle: R,
    plain: 'Custom UI components expose correct name, role, state, and value to assistive tech.',
    failure: 'A div toggle with no role="switch" and no aria-checked, announced as plain text.',
    components: ['custom'], siteTypes: 'all', auto: 'partial' },
  { id: '4.1.3', name: 'Status Messages', level: 'AA', principle: R,
    plain: 'Status messages are announced to assistive tech without moving focus.',
    failure: 'An "Added to cart" toast that screen readers never announce.',
    components: ['custom'], siteTypes: 'all', auto: 'manual' },

  // Modal / dialog reinforcement (mapped to 4.1.2)
  { id: '4.1.2-modal', name: 'Name, Role, Value — Dialogs', level: 'A', principle: R,
    plain: 'Modals use role="dialog"/aria-modal, are labeled, and manage focus correctly.',
    failure: 'A "modal" that is just a positioned div with no role and background still focusable.',
    components: ['modals'], siteTypes: 'all', auto: 'partial' },

  // Table reinforcement (mapped to 1.3.1)
  { id: '1.3.1-table', name: 'Info and Relationships — Data Tables', level: 'A', principle: P,
    plain: 'Data tables use proper header cells, a caption, and header association.',
    failure: 'A data table built from divs, giving screen readers no row/column context.',
    components: ['tables'], siteTypes: 'all', auto: 'partial' },

  // PDF reinforcement (mapped to 1.1.1)
  { id: '1.1.1-pdf', name: 'Non-text Content — Documents', level: 'A', principle: P,
    plain: 'PDFs and downloadable documents are tagged, have reading order, and alt text on images.',
    failure: 'A scanned PDF invoice with no text layer and no tags — unreadable to screen readers.',
    components: ['pdf'], siteTypes: ['government', 'ecommerce', 'saas'], auto: 'manual' },
];
